//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihailenko_Glazki_save
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class Agent
    {
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }
    
        public int SaleCount
        {
            get
            {
                return ProductSale.Count;
            }
        }
        public string TypeAgent
        {
            get
            {
                return AgentType.Title;
            }
        }

        public int SaleForYear { 
            get
            {
                int s = 0;
                foreach(ProductSale p in ProductSale)
                {
                    TimeSpan differenceWithoutTime = DateTime.Today.Date - p.SaleDate.Date;
                    if ((int)differenceWithoutTime.TotalDays > 1)
                        s += p.ProductCount;
                }
                return s;
            }
        }

        public decimal Sales
        {
            get
            {
                decimal s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    s += p.Stoimost;
                }
                return s;
            }
        }

        public int Discount
        {
            get
            {
                if (this.Sales >= 500000)
                    return 25;
                if (this.Sales >= 150000)
                    return 20;
                if (this.Sales >= 50000)
                    return 10;
                if (this.Sales >= 10000)
                    return 5;
                return 0;
            }
        }

        public string FonStyle
        {
            get
            {
                if (Discount > 25)
                    return "LightGreen";
                else
                    return "white";
            }
        }
        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
